"$schema" = 'https://starship.rs/config-schema.json'

palette = 'goth'

format = """
[](surface0)\
$os\
$directory\
[](fg:surface0 bg:surface1)\
$git_branch\
$git_status\
[](fg:surface1 bg:surface2)\
$time\
[](fg:surface2)\
$fill\
$cmd_duration\
$line_break\
$character"""

add_newline = true

[palettes.goth]
surface0 = '#15151d'
surface1 = '#23232d'
surface2 = '#31313d'
text     = '#b6b6c2'
subtext  = '#5a5a6c'
blood    = '#9a3b48'
ash      = '#6e6e7e'

[fill]
symbol = ' '

[os]
disabled = false
format = '[ $symbol ]($style)'
style = 'fg:subtext bg:surface0'
[os.symbols]
Macos = ''

[directory]
format = '[ $path ]($style)'
style = 'fg:text bg:surface0'
truncation_length = 3
truncation_symbol = '…/'
read_only = ' '
read_only_style = 'fg:blood bg:surface0'

[git_branch]
symbol = ''
format = '[ $symbol $branch ]($style)'
style = 'fg:blood bg:surface1'

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = 'fg:blood bg:surface1'

[time]
disabled = false
time_format = '%H:%M'
format = '[   $time ]($style)'
style = 'fg:subtext bg:surface2'

[cmd_duration]
min_time = 500
format = '[  $duration ]($style)'
style = 'fg:ash'

[character]
success_symbol = '[ ❯](bold fg:ash)'
error_symbol = '[ ❯](bold fg:blood)'
vimcmd_symbol = '[ ❮](bold fg:blood)'
